# Site settings
title: Axel's blog
email: rockaxel@gmail.com
description: Juste un blog
baseurl: '' # the subpath of your site, e.g. /blog
url: http://axelrock.fr # the base hostname & protocol for your site
twitter_username: nineties_panda
github_username: axel-rock
instagram_username: axel.rock

# Build settings
markdown: kramdown
permalink: /:title/
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging

# Pagination
paginate: 12

defaults:
-
  scope:
    path: ""
    type: pages
  values:
    layout: page
-
  scope:
    path: ""
    type: posts
  values:
    layout: post
    author: axel
-
  scope:
    path: ""
    type: drafts
  values:
    layout: post

# SASS
sass:
  sass_dir: _sass
  style:   :compressed

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  axel:
    name: Axel Rock
    display_name: Axel
    bio: Salut, moi c’est Axel, bidouilleur numérique. D’après mon diplôme de l’école des Gobelins, je suis officiellement Concepteur Réalisateur Multimédia. Dans les faits, je suis spécialisé dans le développement de sites web et applications en tout genre. Mais je m’intéresse aussi beaucoup à la photo, la vidéo, le design et l’écriture.
    gravatar: /images/avatar.jpg
    email: rockaxel@gmail.com
    web: http://axelrock.fr
    twitter: nineties_panda
    github: axel-rock
    instagram: axel.rock