name:               Axel's blog
description:        Juste un blog
author:             'Axel Rock'
meta_description:   "Axel's blog"

permalink:          /:title/

aboutPage:          true

markdown:           kramdown
highlighter:        pygments

gems:               [jekyll-paginate]

paginate:           100

baseurl:            /
domain_name:        'http://axelrock.fr'
google_analytics:   'UA-57150980-1'
disqus:             false
disqus_shortname:   'your-disqus-shortname'

# Details for the RSS feed generator
url:                'http://axelrock.fr'

social: 
    twitter:        'nineties_panda'
    instagram:      'axel.rock'
    mail:           'axel@rock.bzh'
    # github:         'axel-rock'
    # facebook:       'axel.rock.reight'
    # stackoverflow:  'http://stackoverflow.com/users/2075621/axel-rock'
    # slack:          'bannerboy.slack.com'
    # youtube:        'axelrock'
    # codepen:        'axelrock'
    # apple:          'axelrock'
    # medium:         'axelrock'

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

# SCSS

sass:
  sass_dir:         _sass
  style:            :compressed